# Generated by Django 5.0.2 on 2024-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmodel',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='logmodel',
            name='procedure_date_day',
            field=models.DateField(default='2024-03-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logmodel',
            name='procedure_day_hours',
            field=models.TimeField(default='16:14:30'),
            preserve_default=False,
        ),
    ]
